# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1 #this installs node and npm for us
        with:
          node-version: '12.x'

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2 
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install
        # if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build -- --prod
      - name: Test
        run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage
      - name: Commit coverage
        uses: EndBug/add-and-commit@v5
        with:
          message: "Code Coverage"
          add: "coverage -f"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
